<?xml version="1.0" encoding="UTF-8"?><testrun name="ProductTestCase" project="OnlineShoppingBackend" tests="4" started="0" failures="0" errors="1" ignored="0">
  <testsuite name="com.niit.test.ProductTestCase" incomplete="true">
    <error>org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory' defined in com.niit.OnlineShoppingBackend.config.ApplicationContextConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.hibernate.SessionFactory]: Factory method 'getSessionFactory' threw exception; nested exception is org.hibernate.exception.GenericJDBCException: Unable to open JDBC Connection for DDL execution&#13;
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)&#13;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)&#13;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)&#13;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)&#13;
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)&#13;
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)&#13;
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)&#13;
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)&#13;
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)&#13;
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)&#13;
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)&#13;
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)&#13;
	at com.niit.test.ProductTestCase.init(ProductTestCase.java:27)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:497)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.hibernate.SessionFactory]: Factory method 'getSessionFactory' threw exception; nested exception is org.hibernate.exception.GenericJDBCException: Unable to open JDBC Connection for DDL execution&#13;
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)&#13;
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)&#13;
	... 27 more&#13;
Caused by: org.hibernate.exception.GenericJDBCException: Unable to open JDBC Connection for DDL execution&#13;
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)&#13;
	at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:69)&#13;
	at org.hibernate.tool.schema.internal.exec.ImprovedExtractionContextImpl.getJdbcConnection(ImprovedExtractionContextImpl.java:60)&#13;
	at org.hibernate.tool.schema.extract.internal.SequenceInformationExtractorH2DatabaseImpl.extractMetadata(SequenceInformationExtractorH2DatabaseImpl.java:35)&#13;
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.initializeSequences(DatabaseInformationImpl.java:65)&#13;
	at org.hibernate.tool.schema.extract.internal.DatabaseInformationImpl.&lt;init&gt;(DatabaseInformationImpl.java:59)&#13;
	at org.hibernate.tool.schema.internal.Helper.buildDatabaseInformation(Helper.java:132)&#13;
	at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.doMigration(AbstractSchemaMigrator.java:92)&#13;
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:183)&#13;
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:72)&#13;
	at org.hibernate.internal.SessionFactoryImpl.&lt;init&gt;(SessionFactoryImpl.java:309)&#13;
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:445)&#13;
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:710)&#13;
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:726)&#13;
	at org.springframework.orm.hibernate4.LocalSessionFactoryBuilder.buildSessionFactory(LocalSessionFactoryBuilder.java:372)&#13;
	at com.niit.OnlineShoppingBackend.config.ApplicationContextConfig.getSessionFactory(ApplicationContextConfig.java:60)&#13;
	at com.niit.OnlineShoppingBackend.config.ApplicationContextConfig$$EnhancerBySpringCGLIB$$eb468f1.CGLIB$getSessionFactory$2(&lt;generated&gt;)&#13;
	at com.niit.OnlineShoppingBackend.config.ApplicationContextConfig$$EnhancerBySpringCGLIB$$eb468f1$$FastClassBySpringCGLIB$$21d40ac8.invoke(&lt;generated&gt;)&#13;
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)&#13;
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)&#13;
	at com.niit.OnlineShoppingBackend.config.ApplicationContextConfig$$EnhancerBySpringCGLIB$$eb468f1.getSessionFactory(&lt;generated&gt;)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:497)&#13;
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)&#13;
	... 28 more&#13;
Caused by: org.h2.jdbc.JdbcSQLException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-192]&#13;
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)&#13;
	at org.h2.message.DbException.get(DbException.java:168)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:187)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:167)&#13;
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:99)&#13;
	at org.h2.engine.Database.getPageStore(Database.java:2463)&#13;
	at org.h2.engine.Database.open(Database.java:692)&#13;
	at org.h2.engine.Database.openDatabase(Database.java:270)&#13;
	at org.h2.engine.Database.&lt;init&gt;(Database.java:264)&#13;
	at org.h2.engine.Engine.openSession(Engine.java:64)&#13;
	at org.h2.engine.Engine.openSession(Engine.java:176)&#13;
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)&#13;
	at org.h2.engine.Engine.createSession(Engine.java:137)&#13;
	at org.h2.engine.Engine.createSession(Engine.java:27)&#13;
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)&#13;
	at org.h2.jdbc.JdbcConnection.&lt;init&gt;(JdbcConnection.java:118)&#13;
	at org.h2.jdbc.JdbcConnection.&lt;init&gt;(JdbcConnection.java:102)&#13;
	at org.h2.Driver.connect(Driver.java:72)&#13;
	at java.sql.DriverManager.getConnection(DriverManager.java:664)&#13;
	at java.sql.DriverManager.getConnection(DriverManager.java:208)&#13;
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153)&#13;
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144)&#13;
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196)&#13;
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159)&#13;
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)&#13;
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180)&#13;
	at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:43)&#13;
	... 52 more&#13;
Caused by: java.lang.IllegalStateException: The file is locked: nio:C:/Users/mruser/OnlineShopping.mv.db [1.4.192/7]&#13;
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:773)&#13;
	at org.h2.mvstore.FileStore.open(FileStore.java:172)&#13;
	at org.h2.mvstore.MVStore.&lt;init&gt;(MVStore.java:344)&#13;
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2893)&#13;
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:154)&#13;
	... 75 more&#13;
&#13;
</error>
    <testcase name="CreateProductTestCase" classname="com.niit.test.ProductTestCase" incomplete="true"/>
    <testcase name="DeleteProductTestCase" classname="com.niit.test.ProductTestCase" incomplete="true"/>
    <testcase name="GetAllProductTestCase" classname="com.niit.test.ProductTestCase" incomplete="true"/>
    <testcase name="GetProductTestCase" classname="com.niit.test.ProductTestCase" incomplete="true"/>
  </testsuite>
</testrun>
